### PR TITLE
Mint Intuit Form completed with the minimum asked requirements.

### PR DESCRIPTION
**Pull request by fdfragoso**

### CODE REVIEW

**Comment by Oluwadamilareolusakin** [comment]
# Great work team!

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @fdfragoso and @Kevinalvesdev ! :medal_military: 
I really like your project! Please consider my comments below, make the necessary changes and request another review :ok: 

#### Stickler Config
It seems like you have the wrong stickler config in your file, please look [here](https://github.com/microverseinc/linters-config) for the configuration tailored to the HTML and CSS section instead 

#### Unrelated project files
Please consider adding files and folders not related to the project to your `gitignore`. For instance your `node_modules` shouldn't show up on Git. Please make the required changed before your next review :handshake: 

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by fdfragoso** [comment]
All the requirements for the mint intuit are done;
Added image sprite sheet;
Added animations with an external tool (check readme).

**Review by rOluochKe — APPROVED** [review]
Hello Team,
### Good job so far :clap: and for making changes from previous reviews. Your project looks good. I, therefore, your project. Congratulations :boom: :100:
### You can merge and submit a project form from your dashboard. Good luck in the next project.
- Happy coding!

**Pull request merged**
